spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: 0244f86357eb4320a180f4f30020900d
            client-secret: c637c7d891b0435c9d2d0e58c928a866
            scope: user-top-read
            provider: spotify-provider
            #redirect-uri: http://localhost:8080/login/oauth2/code/spotify
            redirect-uri: https://annas-plugin.herokuapp.com//login/oauth2/code/spotify
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          spotify-provider:
            token-uri: https://accounts.spotify.com/api/token
            authorization-uri: https://accounts.spotify.com/authorize?show_dialog=true
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id